### PR TITLE
Add all screen builders

### PR DESCRIPTION
**Pull request by KunLW**

### CODE REVIEW

**Review by tlan4 — DISMISSED** [review]

**Review by tlan4 — APPROVED** [review]

**Review by tlan4 — APPROVED** [review]

**Review by lungerjo — COMMENTED** [review]
Do you want the login use-case to build the appropriate screen? Or were you intending to handle that logic in main?

**Review by tlan4 — COMMENTED** [review]
What is CheckProfile for?

**Review by zeyuzhang516 — APPROVED** [review]
Good work! The code follows the clean architecture, and it helps us build all the screens., connecting the use case with the framework. Thanks a lot!

**Review by GitHaoBao — APPROVED** [review]

**Review by lungerjo — APPROVED** [review]
I see, the UI logic will get handled at the level of the UI, not the frameworks/drivers, so the login response model does not need to be passed to main. Also because Curr is static.

**Pull request closed without merging**
